### PR TITLE
feat: Set BASHER_PACKAGES_PATH with init

### PR DESCRIPTION
**Pull request by pawamoy**
Implements issue #68.

### CODE REVIEW

**Comment by pawamoy** [comment]
The commit that updates tests simply shifts line numbers since I added a line in between. I also make sure `basher-init` outputs the export line, and finally I added two tests in *basher.bats* to make sure the `BASHER_PACKAGES_PATH` variable is inherited from environment, or based on `BASHER_PREFIX`.

**Comment by juanibiapina** [comment]
What if `basher` doesn't reexport the variable if it is already there? That means the line is only present is the user did not set it.

**Comment by pawamoy** [comment]
But it does: in `basher`:

```bash
if [ -z "$BASHER_PACKAGES_PATH" ]; then
BASHER_PACKAGES_PATH="$BASHER_PREFIX/packages"
fi
export BASHER_PACKAGES_PATH
```

Notice that in any case the variable is exported.

Or I'm not sure to understand what you mean?

**Comment by juanibiapina** [comment]
Ah I see. There is no clean way when inside the `init` command to determine if the variable was set by the user or by basher itself. It's ok then, this is simpler.

**Pull request merged**
