### PR TITLE
Fix #59

### LINKED ISSUE #59: Error while running tests on OS X
I keep getting these failures during the basher test run on OS X.  There isn't a lot of info about what the actual error is, what code is being run, etc.

```
 ✓ extracts only usage
 ✓ multiline usage section
 /var/folders/vv/yvb4m22n5f511tbzjjjwcm240000gn/T/bats.44779.src: line 66: syntax error near unexpected token `>'                                                                                                                    51/119
 ✓ multiline extended help section

119 tests, 0 failures

make: *** [test] Error 1
```

### PR DESCRIPTION
**Pull request by kadaan**
Change bash4+ code to a form that supports bash 3+
Change travis config to run tests agains multiple linux bash versions and OS X (like bats-core)

### CODE REVIEW

**Comment by kadaan** [comment]
@pawamoy Hopefully you will be able to add an alpine docker test so we can automatically cover all our bases.

**Comment by kadaan** [comment]
@juanibiapina Also, it would be nice if we integrated new version publishing of tags that succeed all the tests on all platforms.

**Comment by pawamoy** [comment]
@kadaan I see you're basing your Dockerfile on `bash`, which is based on Alpine, so you got me covered I guess :slightly_smiling_face:

**Comment by kadaan** [comment]
> @kadaan I see you're basing your Dockerfile on `bash`, which is based on Alpine, so you got me covered I guess 🙂

@pjeby Seems like this alpine based box works without your changes. It would be good to get a base alpine box like you use in as a docker based test.

**Comment by juanibiapina** [comment]
This is awesome!

**Comment by pjeby** [comment]
There seems to be a problem with the OS X testing here.  The travis build passes, but manually running the test with a fresh checkout on stock OS X produces 7 errors of the form:

```
   -- command failed --
   status : 1
   output (2 lines):
     readlink: illegal option -- f
     usage: readlink [-n] [file ...]
```

This seems to mean that travis includes either `realpath` or a GNU-style `readlink` on the `PATH`, but stock OS X does not have either AFAIK.  Any thoughts?

**Comment by kadaan** [comment]
@pjeby Not sure what is happening.  I added a test branch that calls `readlink -f` and it fails.  Not sure why the basher tests pass...

https://travis-ci.org/kadaan/basher/jobs/488661472

**Comment by pawamoy** [comment]
Wouldn't that be fixed with @pjeby 's PR? What if you rebase your PR to include this Travis config, to see how the tests run?

**Comment by kadaan** [comment]
@pawamoy Yeah, it should.  Thing is, the tests should be failing now on OS X.

**Comment by pjeby** [comment]
@pawamoy: the problem here isn't about fixing the readlink issue, it's about *testing* it.  Since the travis tests pass on OS X but fail elsewhere, it means the tests are not properly testing OS X.

As for what's going on, since `readlink -f` "successfully" fails on Travis, that means that Travis's OS X environment must include a `realpath` executable on the `PATH` somewhere (otherwise the tests would use `readlink -f` and fail.).  I suppose the script could do a `sudo rm -f "$(command -v realpath)"` or something, so that the test would then fail successfully. :wink:

**Comment by kadaan** [comment]
@pjeby I thought Travis was providing it too, but that doesn't explain this: 
```shell
x test/test_helper.bash
readlink: illegal option -- f
usage: readlink [-n] [file ...]
1..119
ok 1 without arguments prints usage
```
I created a branch and changed .travis.yml to the following:
```
...
readlink -f bats/bin/bats
git config --global user.email "user@example.com"
git config --global user.name "User Name"
time bats/bin/bats --tap tests
...
```
As expected, it prints that readlink -f is not supported when run by Travis on OS X.  But then the tests run and they all pass...

**Comment by pjeby** [comment]
Try `realpath` instead.  Basher doesn't use  `readlink -f` unless `realpath` is **not** found.  Since the tests are succeeding, there must be a `realpath` available under Travis, even though there is not one on stock OS X.

**Comment by kadaan** [comment]
I can fix it.  I think for darwin we need to run `brew uninstall --force coreutils`

**Comment by pjeby** [comment]
I've done that and the tests pass, but of course they already did anyway, so that doesn't really test that the tests fail *without* my PR.  :wink:

**Comment by kadaan** [comment]
Yup, I know, but this showed it fail: https://travis-ci.org/kadaan/basher/jobs/488717569

**Pull request merged**
