### PR TITLE
Install a specific branch or tag with `@` syntax

### PR DESCRIPTION
**Pull request by YarekTyshchenko**
Modify install command to take `package@ref` style syntax. This should
be idiomatic for everyone.

The ref selection is permanent, theres no way to switch the package
to a different ref without re-installing it.

### CODE REVIEW

**Comment by YarekTyshchenko** [comment]
I think `basher outdated` will break if remote is older than local master, but `basher upgrade` will fail before then 😉  `git pull` wont know how to handle that!

**Comment by juanibiapina** [comment]
This is great! I'll take a better look this week, but it seems exactly what I had in mind.

**Comment by juanibiapina** [comment]
For me running `basher outdated` after installing bripkens/dock@v1.2.0 still gives an error. There should be a test for this case.

**Comment by YarekTyshchenko** [comment]
You are right. Let me see if I can clean that up

**Comment by juanibiapina** [comment]
This is really great. Thanks and sorry for the delay.

**Pull request merged**
