### PR TITLE
Change include function to not include the same file twice

### PR DESCRIPTION
**Pull request by juanibiapina**
Replaces #37

@pjeby @hugot @pawamoy

### CODE REVIEW

**Comment by pawamoy** [comment]
Yes, looking good to me. Ultimately the included files are double-space separated, and there is very little chances someone uses *double* spaces in filenames, so it should not even break with simple spaces in filenames.

**Comment by juanibiapina** [comment]
I still don't like it though. A file can have two spaces. The only character I can see safely being used is the null separator.

**Comment by pawamoy** [comment]
There's still the possibility to encode the contents of the variable with `base64`, to avoid this delimiter corruption issue, but it would surely bring other issues...

**Comment by juanibiapina** [comment]
another option is to use a very unlikely pattern like ` : # : `

**Comment by juanibiapina** [comment]
another option is to use this solution only for `sh`, and do separate solutions for other shells using arrays.

**Comment by pawamoy** [comment]
Yep. Damn `sh` not supporting arrays :D

**Comment by juanibiapina** [comment]
That a good point. In that case I think I will separate the implementation per shell and white the `sh` version using `\n` as a separator.

**Comment by juanibiapina** [comment]
> That a good point. In that case I think I will separate the implementation per shell and write the `sh` version using `\n` as a separator.

Does any feel like implementing this?

**Comment by juanibiapina** [comment]
If anyone is still interested, I think the way to go is to provide shell specific implementations:
- bash and zsh: arrays
- sh: using `\n` ou `null` as a separator

For now I'll close this since I don't need this feature.

**Pull request closed without merging**
