### PR TITLE
Fetch repo description with basher list and fix readme

### PR DESCRIPTION
**Pull request by danog**
I've added the function in basher-list to fetch the repo description from github and print it after username/package.
I've also removed the $ in front of commands in the readme to facilitate copying and pasting.

### CODE REVIEW

**Comment by juanibiapina** [comment]
I'm not inclined to accept this pull request. It has two different changes and the commits could use some clean up, but mainly I disagree with the changes:

1. The dollar sign in front of shell commands is a common way to identify these are commands to execute as a normal user. Most projects use it like this (example [https://github.com/rbenv/rbenv](rbenv)).

2. Listing has become very slow, since it has to pull descriptions for several projects. Also I find slightly weird to pull descriptions for projects I already installed.

3. There is a bug and the "\t" is not printing correctly.

Pulling descriptions for projects could be a useful feature separately somehow, although I still don't see how. Maybe combined with some sort of search.

**Comment by danog** [comment]
Hmm, I agree with most of your points.
1. I've put back the dollar signs
2. What about adding an option? Like basher list -d to also get the descriptions.
3. I was thinking of creting an index of some sort (with an Openshift app).
What do you think of that?
And I've fixed the tab.

**Comment by juanibiapina** [comment]
Leaving the index aside for now, what is the specific use case you would like to solve?

**Comment by danog** [comment]
Well, it was just an idea. I didn't want solve any specific use case.

**Comment by juanibiapina** [comment]
I'm gonna close this issue for now, since I don't know how to use repo descriptions for something useful. I might return to this in the future though, if there are compelling ideas.

**Pull request closed without merging**
