### PR TITLE
Enable recursive cloning

### PR DESCRIPTION
**Pull request by beevelop**
this allows packages to make proper use of submodules

### CODE REVIEW

**Comment by juanibiapina** [comment]
I like it, but could you please make a few changes?

1. Merge the two commits
2. Change the commit description to start with a capital letter and end with a "dot"
3. Add a max-depth option to avoid infinite loops or incredibly deep hierarchies (10 should be fine I guess)

**Comment by beevelop** [comment]
Yeah sure. Do you know of a way to limit the recursive deepness? `--depth` does only limit the number of revisions cloned. I am not aware of an option like `max-depth`.

**Comment by juanibiapina** [comment]
It seems there really isn't. I must have gotten it confused at some point. Ignore point 3 xD

**Comment by beevelop** [comment]
Alright, I squashed the commits and updated the commit message.

**Comment by juanibiapina** [comment]
I meant the commit description, not the title :(

**Comment by juanibiapina** [comment]
Your original commit message was better because it had a little explanation for the feature.

I have now started a CONTRIBUTING.md to make it easy for people to contribute.

I also ask you now rebase with master.

**Comment by beevelop** [comment]
There you go

**Pull request merged**
